# Generated by Django 4.2.5 on 2024-01-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mobile_number',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
