# Generated by Django 4.2.5 on 2024-01-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0003_booking_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='qr_code',
        ),
    ]
